# Generated by Django 5.1.4 on 2024-12-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('home_place', models.CharField(max_length=100)),
                ('home_church', models.CharField(max_length=100)),
                ('current_place', models.CharField(max_length=100)),
                ('current_church', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='singers_photos/')),
                ('audio_song', models.FileField(upload_to='audio_songs/')),
                ('video_song', models.FileField(upload_to='video_songs/')),
            ],
        ),
    ]
