# Generated by Django 5.1.4 on 2024-12-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choir', '0002_remove_singer_audio_song_remove_singer_video_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
