# Generated by Django 5.1.4 on 2024-12-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choir', '0003_alter_singer_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='voice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
